version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      Fb54BoC2YmgLbGmwdnZxDLroRJcH7zBnRkLjILwklQpGKYq4jfHjgr6zGR3yhQv2ehBi7S7c6u8KaELKUPKNUU4mAsil/QNzEuV6Pvnl+j3PyLAsQth5OXsH1Sk4lu/AXtzTO8ZDJ9DCx7NQZtIZSOKF27GKpMuuGUmgjcmDm+IA8zNL3CK3FCjFQC6DadQgE8SjYyZkwvHqOx5d2Ui+8r6w7bV9DbhyAA03X+/pI7FuXYxauOjSURRP2Y8EY0f96rPuY4qWQ0+x5OC1sxekszIP5/IAaXthpD9bhvebIyp8pPb6RNDCaJ/CWk9sG49Ei/z7EMxaxarJ9ADQdPT7e8sYbOvWvGlyXAMoP8EAANcqx0g3MPuSHI2QZ6VYd7LyxlCTWMQaEPf6pksrebH4rjSqp2PRGXmKUOZhqA3Zn+l4lnNS2jzLb0ILxfhqwXYH58PH+cbVL3+iYT+bkT1VdbzKeepni/crsygLCwf2NE0U7ThzsbBB5fuEoGdFB8ibKPSwuMMooSayp4E5QPK5bSMU56FRo1vLCQe9jY7Gj3mpyyFseUpiK282/pF5DINMesIc9WxSSEmdTJ8vAygcLoKewfUKXcQfb3RCL3eIreR9AknsV4ZsbLd5z2g08P/gXvsS5MSXcPox67RxNNSlFA5Ortp7BG7E3PgU9PcVjQA=
