version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      NgU8kfIBpqqV/ZpYFGE+dy48lEbOzTNn+VTD+XplVphSWPS1SELbwrfoRC5nFzexcTv0v5X+monUTwBbeef6OQH3b5/PritOf/eHgOyiXpdz+JYx4sZWklO0ZNHnj6NYanxu5+Lscxw+EMEwBgmOl3QBEoE1ef3gE3vkGM1qPc8++psKLPmdgyHLppbRRkZTvDZh0HcEzRHDOwXrElPGqaNWazQjwaUd+ui1aLTiia5n3JZ1wlpja4HVd5xNDLDAK1EKxZ5mtA3+ZreNB97gFaCbHLc1if1z414sWHHN9YCPBBjbNZ7gn5AXS1/IxdXEHDjxPPdnwjjXRI9SLWdAgDWFmnKumOQKPsvGjAtqMjDvMAf4//UPdOXqG0Hwi1niArv3g21Kj3FF8z6+odH0d9YRwBgPJ0gBoQQvj2mzd8+u3KdRxqvOJ2UJb/pOcSE4Zqm7HrooG5z4yvBYqm4ZUesvdmc9OZ0Wv3pAn3zppCY/Kck8xQ24/ji0vzUs6SCnJr3HQxM9u6bp/bhx7lrvMyJlv23DgkKpXMZ9D2wVrKvCf2MPrwnrgFaVEFTkUjckL7XU0kESbhXHnUTHSsetC1IBTy2izvXQ/lbJyZQokFdxlQN0oK4StGJjuVo8S1UiH5yo83X4ivRAKfkRstkhzWoSebE5Ou18RUDZQa5QODM=
