sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: dg+1DzlZVNREqi2QY4FM4SuRlAs9Nyazu5J5hrLcVQh/08Fs3YQwuGkX8clCn7zxkokG9BGMUj0AsNqGe7saRpGqR9agUK2AOPJD7AQysZDG06s8iUFUAjWf3hZqb3uNIt0k0alZSIUaU43RxH6mlVnyKjIQ2ZXxObdeknXIwntpJbUhq90ZwBpKtBBCs+z0Pgm7NYUVGU/gF8a5EF0LdDNug+Mz2oQ1iNzWFgenI8erRaARlc5KG2o3r5E8PXGjgwRDQy71VZ3CNHjciGKAt6zbbEflvQBv3R1bo7b+Gp80+14GsS9vy3OcTd+p5fYmcAByvoubj/Wa52RzKSdO8vtO37YK3Vbyvuf8JfHSyFykl7DvXFCfkuMoF+em7FwIJNo49dl3bRfJVZYVVrpZoRNkOZ1EgFyi7ZReAImZ/q+ybEL/XuOBcB9HhQJFJLdTSvGWLbvHy/EzyLWEbfePRXTpLJVnG0EWN/oDv6WXC/OIsKqX23ttxJbuG8is1YKXVsMJ2ejpPVCnuyuDuvLRrRAqy1YaYXJ5fzHUUBN2rRstC+GRVpSHDDIZOA10CuSW8AJe/GsowXQQKnIXYYzcf8eiO9byIugUPVx3NADAcX1evv+6TT5p3kfs6OTBw7pM+lNeZFAJqD6kvejO6714w2zjfQrexLkj7qxeCmylegk=
