version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      RAeBTg3QJzsQSSzr3WoB9ZBdm73Oa5MHjkHQbG4MdPqEaWziL9a3Mi+oSmNTBMFCDwpD5vTb/K+uMOj9tzHYNFyFnho4YGGZhouDXKIldHOUAY0Kig1tgknqQKFZqDIOhLoy/yXknMHQGHxgvP1mdvdDV4y4Kh1UDrTW9jNJUIeiRoCKqaeLsUBx3cQ3GsEok94XshEgKDqgXJ7p3WvFYgwp2Bl14Gy9LzJZwF7wRXTVPNB+w2ipVzIendDkJ/tHoipVgiPYOiakiPO6CaOuKUcD9wU9v2AZ9bG1WL3NJ6o0UCrJ+Uh+F1FofjyVzCuc8sf71myPTZt7J1r7qXijeOfreXzxpBby52Zl1UQu7FKdK7nL1iejn6vJx4T9aNXrde1WiG41NDl5e/c9fMlF6G1krJGkwlnNYrFMnmlsZ5gdA8222ycdb0dkOW1QNq4MhheoRpLL6z5CD1Bheak84E3D1qAAhtPif6NIn3pwpPVwjmc1KQTIr/v2lZmT9gdrXVuhs7ZSZSWNR5a1QlQnJp9uS9eUrU8+yXgtMLgr7JYhmp3kr/0n1TVMXcEKInrTAdCHFyx5cqzdDneHW6ZlVi3ROyf+gm8uP6nP+gBqckiuXI6pru1uPiUYv2Gs7DLmR71LQbN8FzFzC/VXOAZBFbhDatjBfT0fjf6JjJcQ23E=
