version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      hBk46eQLBhWQgS+CI/6dHvRJaOwm89SsXUyHTeV/nSPwnZ4L/jnafetLmFov0Bv2FRvYVzZkLxfN8z/wItR4TENfuw5deCCd28A6tzM5L2hH7BlppxFQv+JSINKmLiIdA9tCQraqyAGZN8ZsYnlaDfx0+YUzMA/GYfei7V9jpBX9+11DZmdUltqjUmqrhk0e7Q7nF/4+dnkPdn0iepNGWfTz2BKVGKtGkb3Ac4ZBXwFEHIFjkEtpofmGcu6sZZXGBRKHhg9GD/oKTaOHHhvEKcYT29h4ybYdmQmausKXvclJmzUQB75qdzJXOfvw6TIDT9ahZFPUmrAtpX/n5I4pTj4azVuF12WiRJuY0c4FaO5LD6blgmqWCOgkHOr2iMkfJeVHODbl/XgldGodqXMr8fMtKQoSfFE5M4kaxABNMfny+oQev6ceSuiaxd5Q8lE8ICddWwXnnZPfbFokOmI0O0ZLTkIPjKmAhMNnf8zBoUKhDAj35KM068HEFJvusV39Wtzc0YGjxzNAqsT7i4+2/V7qehudW/Qu0/xqyc0GIzVnJvRLdHbhiJW+QYO8Qe7ZvvcfOVxeJ0cdVsfhBveReejPmtuq3Qkj06odexgYuBwbRHSJmwkq8B6vodm/BXWHUmdr2eQweG7Z4UOKBk+T1J2HCvjJ6+oeQWgHtwGy2Kw=
